# META
# baseurl: # only set if page is in /directory 
description: fratzhengeballer + gesichtskirmes
domain: fratzengeballer.eu
url: "https://www.fratzengeballer.eu"
email: chris.rocholl@pm.me
encoding: utf-8
locale: "en-EN"

# COLLECTIONS
include: 
   - _pages

# PERMALINK pretty - /:categories/:year/:month/:day/:title/
permalink: pretty

# PLUGINS
plugins:
   - jekyll-feed
   - jekyll-seo-tag 

# BUILD
kramdown:
   input: GFM

markdown:
   kramdown
     
sass:
  style: compressed

timezone: Europe/Berlin

theme: null
